name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Before you submit
      options:
        - label: "I have checked the wiki to make sure this feature does not already exist."
          required: true
        - label: "I have asked in the Discord server to see if others have found a workaround."
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "Example: There is no way to run a command when a panel is closed."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you have considered (optional)
      description: Any alternative solutions or workarounds you have already tried or thought about.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or videos (optional)
      description: Drag and drop files or paste links if applicable.

  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to submit a feature request!