# |------------------------------------------------------------------------
# |                       CommandPanels Config File
# |                           By RockyHawk v8
# |               https://www.spigotmc.org/resources/67788/
# |
# |------------------------------------------------------------------------

# When disabled, custom commands to open panels will not be registered
custom-commands: true

# Amount of time in ticks players must wait between opening panels
cooldown-ticks: 5

# Logs to console whenever a panel is opened
panel-snooper: false

# When enabled, panels will automatically refresh if any observed permissions change.
# An observed permission is a permission used in conditions with $HASPERM
permission-observer: true

# When enabled, panels will automatically refresh if any observed placeholders change.
# Avoid if you have placeholders in conditions that constantly change (eg RNG placeholders).
condition-observer: false