version: 3.15.2.3
main: me.rockyhawk.commandpanels.CommandPanels
name: CommandPanels
author: RockyHawk
api-version: '1.13'
description: Fully Custom GUIs. Make your Server Professional.
softdepend: [PlaceholderAPI, Vault, HeadDatabase, TokenManager, VotingPlugin, MMOItems, CustomItems, ChestSort]
commands:
   commandpanel:
      description: Open a command panel.
      usage: /commandpanel <panel> [player:item] [player]
      aliases: [cp, cpanel]
   commandpanelreload:
      description: Reloads plugin config.
      usage: /commandpanelreload
      aliases: [cpr, cpanelr]
   commandpaneldebug:
      description: Enable and Disable debug mode globally
      usage: /commandpaneldebug
      aliases: [cpd, cpaneld]
   commandpanelblock:
      description: Add or remove panels from blocks being looked at.
      usage: /commandpanelblock
      aliases: [cpb, cpanelb]
   commandpanelgenerate:
      description: Generate GUI.
      usage: /commandpanelgenerate
      aliases: [cpg, cpanelg]
   commandpanelversion:
      description: Display the current version.
      usage: /commandpanelversion
      aliases: [cpv, cpanelv]
   commandpaneledit:
      description: Edit panels ingame.
      usage: /commandpaneledit [panel]
      aliases: [cpe, cpanele]
   commandpanellist:
      description: Lists the currently loaded panels.
      usage: /commandpanellist
      aliases: [cpl, cpanell]
permissions:
   commandpanel.panel.default:
      default: true
   commandpanel.other:
      default: op
   commandpanel.panel.*:
      default: op
   commandpanel.item.*:
      default: op
   commandpanel.reload:
      default: op
   commandpanel.debug:
      default: op
   commandpanel.block.add:
      default: op
   commandpanel.block.remove:
      default: op
   commandpanel.block.list:
      default: op
   commandpanel.generate:
      default: op
   commandpanel.version:
      default: true
   commandpanel.update:
      default: op
   commandpanel.editor:
      default: true
   commandpanel.edit:
      default: op
   commandpanel.list:
      default: op